language: rust
cache: cargo

rust:
  - stable
  - beta

before_script:
  - rustup component add clippy

script:
  # fail when encountering warnings
  - cargo clippy --all-targets --all-features -- -D warnings
  # run tests
  - cargo test
  - cargo build --examples
